### ISSUE TITLE
Fix subclasses taking way longer than they should to be constructed

### ISSUE THREAD

**Issue by vocksel** [vocksel/class#1]
Currently, there's about a 1.46 second difference between vanilla subclassing and our subclassing, over 1 million calls to `class()`.

This is due to the loop we use to copy metamethods from the superclass into the subclass. We currently have a bit of a messy fix for this, but it could still use some more work.

``` lua
local function lookUpMetamethods(subclass, superclass)
  for _, metamethod in ipairs(INHERITED_METAMETHODS) do
    subclass[metamethod] = function(...)
      local method = superclass[metamethod]
      if method then
        return method(...)
      end
    end
  end
end
```

Before we implement this, it needs to be broken down into smaller functions. We might even want to try a different implementation. This was initially from an older version of [Middleclass](https://github.com/kikito/middleclass), and its current source code is vastly different. We might be able to find some inspiration for how to tackle metamethod inheritance in it.

**Comment by Validark** [comment]
Number 1 way to make it faster: remove `ipairs` loops and use simple for loops instead.
